Sails = require('sails')
sails = undefined

global.request = require("supertest-as-promised");
global.should = require("chai").should()

options = {
  loose     : "all",
  stage     : 1,
  ignore    : null,
  only      : null,
  extensions: null
};
require("sails-hook-babel/node_modules/babel/register")(options);

before (done) ->
  Sails.lift {
    environment: 'test'
    port: 1338
    hooks:
      grunt:false
  }, (err, server) ->

    sails = server
    if err
      return done(err)
    # here you can load fixtures, etc.
    done err, sails
    return
  return
after (done) ->
  # here you can clear fixtures, etc.
  sails.lower done()
  return

# ---
# generated by js2coffee 2.0.3
