web:
  image: artificial/docker-sails
  working_dir: /picklete
  command: "/bin/bash -c 'source ~/.bashrc && npm start'"
  ports:
    - "1337:1337"
  volumes:
    - ./:/picklete
  links:
    - mysql

  environment:
    MYSQL_PASSWORD: "picklete"
    MYSQL_USER: "picklete"
    PORT: "1337"
    NODE_ENV: "production"
    DOMAIN_HOST: "shop.agricloud.cc"
  restart: always

mobile:
  image: iojs
  command: "node server.js"
  working_dir: /app
  ports:
    - "3000:3000"
  links:
    - web

  volumes:
    - ../agricloud-mobile-cart:/app
  environment:
    NODE_ENV: "production"
    DOMAIN_HOST: "m.agricloud.cc"
  restart: always


mysql:
  image: dgraziotin/mysql
  ports:
    - "3306:3306"
  volumes:
    - "../database:/var/lib/mysql/"
  environment:
    MYSQL_ADMIN_PASS: "root"
    MYSQL_USER_NAME: "picklete"
    MYSQL_USER_DB: "picklete_prod"
    MYSQL_USER_PASS: "picklete"
    CREATE_MYSQL_BASIC_USER_AND_DB: "true"
  restart: always
