/**
loginRequired

@module      :: Policy
@description :: Simple policy to allow any authenticated user
@docs        :: http://sailsjs.org/#!documentation/policies
 */
module.exports = function(req, res, next) {
  var referer;
  referer = req.path.split('/');
  try {
    if (UserService.getLoginState(req)) {
      let userInfo = UserService.getLoginUser(req);
      if(referer['1'] === 'admin'){
        if (userInfo.Role.authority === 'admin') {
          return next();
        } else {
          return res.redirect('/');
        }
      }else{
        return next();
      }
    }
    if (referer['1'] === 'admin') {
      return res.redirect('/admin/login');
    } else {
      return res.redirect('/');
    }
  } catch (e) {
    if (referer['1'] === 'admin') {
      return res.redirect('/admin/login');
    } else {
      return res.redirect('/');
    }
  }
};

// ---
// generated by coffee-script 1.9.2
