###*
# Passport configuration
#
# This is the configuration for your Passport.js setup and where you
# define the authentication strategies you want your application to employ.
#
# I have tested the service with all of the providers listed below - if you
# come across a provider that for some reason doesn't work, feel free to open
# an issue on GitHub.
#
# Also, authentication scopes can be set through the `scope` property.
#
# For more information on the available providers, check out:
# http://passportjs.org/guide/providers/
###

module.exports.passport =
  local: strategy: require('passport-local').Strategy
  paypal:
    name: 'Paypal'
    protocol: 'oauth2'
    strategy: require('passport-paypal-oauth').Strategy
    options:
      clientID: "AXrDEZYsw5a97a9uRiOasA5wfXpNI5DwyTqlfTZ-8mDWoxMdkn0SdqrP8Qy9kL265rZx0qc8HRNnPwDR"
      clientSecret: "ECHHU3ei6vY_AVz_8HGJTb6i4i4s47DNdq6A4ixVxN150UJ4Vgn940eB6DrVfOiU8-c4s1pw_MtRT-gI"
      sandbox: true
      callbackURL: "http://localhost:1337/auth/paypal/callback"
      scope: [ 'email', 'openid', 'profile' ]
  # bearer: strategy: require('passport-http-bearer').Strategy
  # twitter:
  #   name: 'Twitter'
  #   protocol: 'oauth'
  #   strategy: require('passport-twitter').Strategy
  #   options:
  #     consumerKey: 'your-consumer-key'
  #     consumerSecret: 'your-consumer-secret'
  # github:
  #   name: 'GitHub'
  #   protocol: 'oauth2'
  #   strategy: require('passport-github').Strategy
  #   options:
  #     clientID: 'your-client-id'
  #     clientSecret: 'your-client-secret'
  facebook:
    name: 'Facebook'
    protocol: 'oauth2'
    strategy: require('passport-facebook').Strategy
    options:
      clientID: '1598226980388780'
      clientSecret: '71ae89eba342ce5a48a30a870d6bd473'
      scope: [ 'email' ]
      # callbackURL: "http://localhost:3000/auth/facebook/callback"
  # google:
  #   name: 'Google'
  #   protocol: 'oauth2'
  #   strategy: require('passport-google-oauth').OAuth2Strategy
  #   options:
  #     clientID: 'your-client-id'
  #     clientSecret: 'your-client-secret'
  # cas:
  #   name: 'CAS'
  #   protocol: 'cas'
  #   strategy: require('passport-cas').Strategy
  #   options:
  #     ssoBaseURL: 'http://your-cas-url'
  #     serverBaseURL: 'http://localhost:1337'
  #     serviceURL: 'http://localhost:1337/auth/cas/callback'

# ---
# generated by js2coffee 2.0.3
